import typography from '@tailwindcss/typography'

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      fontFamily: { sans: ['Inter', 'system-ui', 'sans-serif'] },
      colors: {
        'bg-deepest':  'var(--color-bg-deepest)',
        'bg-base':     'var(--color-bg-base)',
        'bg-surface':  'var(--color-bg-surface)',
        'bg-elevated': 'var(--color-bg-elevated)',
        'bg-hover':    'var(--color-bg-hover)',
        'bg-active':   'var(--color-bg-active)',
        'bg-input':    'var(--color-bg-input)',
        'glass-border': 'var(--color-glass-border)',
        'glass-bg':    'var(--color-glass-bg)',
        'text-primary':   'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-muted':     'var(--color-text-muted)',
        'accent':         'var(--color-accent)',
        'accent-hover':   'var(--color-accent-hover)',
        'accent-light':   'var(--color-accent-light)',
        'accent-text':    'var(--color-accent-text)',
        'status-todo':     'var(--color-status-todo)',
        'status-progress': 'var(--color-status-progress)',
        'status-review':   'var(--color-status-review)',
        'status-done':     'var(--color-status-done)',
        'status-blocked':  'var(--color-status-blocked)',
        'row-1':  'var(--row-1)',
        'row-2':  'var(--row-2)',
        'row-3':  'var(--row-3)',
        'row-4':  'var(--row-4)',
        'row-5':  'var(--row-5)',
        'row-6':  'var(--row-6)',
        'row-7':  'var(--row-7)',
        'row-8':  'var(--row-8)',
        'row-9':  'var(--row-9)',
        'row-10': 'var(--row-10)',
      },
      borderRadius: {
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
      },
      boxShadow: {
        sm:   'var(--shadow-sm)',
        md:   'var(--shadow-md)',
        lg:   'var(--shadow-lg)',
        glow: 'var(--shadow-glow)',
        focus: 'var(--shadow-focus)',
        elevated: 'var(--shadow-elevated)',
      },
      transitionDuration: {
        '80':    'var(--duration-80)',
        '100':   'var(--duration-100)',
        '120':   'var(--duration-120)',
        '150':   'var(--duration-150)',
        '180':   'var(--duration-180)',
        '200':   'var(--duration-200)',
        '240':   'var(--duration-240)',
        '300':   'var(--duration-300)',
        '320':   'var(--duration-320)',
        '480':   'var(--duration-480)',
      },
      transitionTimingFunction: {
        spring:   'var(--ease-spring)',
        out:      'var(--ease-out)',
        'in':     'var(--ease-in)',
        'in-out': 'var(--ease-in-out)',
        standard: 'var(--ease-standard)',
      },
      zIndex: {
        raised:  'var(--z-raised)',
        sticky:  'var(--z-sticky)',
        overlay: 'var(--z-overlay)',
        dropdown: 'var(--z-dropdown)',
        'modal-backdrop': 'var(--z-modal-backdrop)',
        modal:   'var(--z-modal)',
        toast:   'var(--z-toast)',
        tooltip: 'var(--z-tooltip)',
      },
      fontSize: {
        'display-xl': ['var(--text-display-xl)', { lineHeight: 'var(--leading-tight)', letterSpacing: 'var(--tracking-tight)' }],
        'display-lg': ['var(--text-display-lg)', { lineHeight: 'var(--leading-tight)', letterSpacing: 'var(--tracking-tight)' }],
        'display-md': ['var(--text-display-md)', { lineHeight: 'var(--leading-snug)',  letterSpacing: 'var(--tracking-tight)' }],
        'display-sm': ['var(--text-display-sm)', { lineHeight: 'var(--leading-snug)',  letterSpacing: 'var(--tracking-snug)' }],
        'heading':    ['var(--text-heading)',    { lineHeight: 'var(--leading-snug)',  letterSpacing: 'var(--tracking-snug)' }],
        'body-lg':    ['var(--text-body-lg)',    { lineHeight: 'var(--leading-normal)' }],
        'body':       ['var(--text-body)',       { lineHeight: 'var(--leading-normal)' }],
        'body-sm':    ['var(--text-body-sm)',    { lineHeight: 'var(--leading-normal)' }],
        'label':      ['var(--text-label)',      { lineHeight: 'var(--leading-normal)' }],
        'micro':      ['var(--text-micro)',      { lineHeight: 'var(--leading-normal)', letterSpacing: 'var(--tracking-widest)' }],
      },
    },
  },
  plugins: [typography],
}
